# Generated by Django 5.2.5 on 2025-08-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
