# Generated by Django 5.2.5 on 2025-08-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytProfile', '0002_canal_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
