# Generated by Django 5.2.5 on 2025-08-31 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytProfile', '0003_remove_canal_categoria_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.CharField(max_length=50, unique=True)),
                ('tematica', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='canal',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canales', to='ytProfile.categoria'),
        ),
    ]
