# Generated by Django 5.2.5 on 2025-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytProfile', '0004_categoria_canal_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='categoria',
        ),
        migrations.AddField(
            model_name='canal',
            name='categorias',
            field=models.ManyToManyField(related_name='canales', to='ytProfile.categoria'),
        ),
    ]
