# Generated by Django 5.2.5 on 2025-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytProfile', '0005_remove_canal_categoria_canal_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#b0b0b0', max_length=7),
        ),
    ]
